/* eslint-disable prettier/prettier */
// https://www.theguardian.com/business/2002/jan/13/corporatefraud.enron
export const contacts = [
{ name: '@enron', aliases: ['Downtown@enron, All Enron', 'Group@enron, Announcement','Houston@enron, Enron', 'Report@enron, Houston Outage', 'Special@enron, All Enron Employees United States','dl-ga-all_enron_worldwide1','dl-ga-all_enron_houston_employees','allemployees','Worldwide@enron, All Enron','Houston@enron, All Enron','Group@enron, All Enron Employees United States',] },
{ name: 'Bannantine, James M', aliases: ['jbannan@enron.com'] },
{ name: 'Baxter, Cliff', aliases: ['Baxter@ect, Cliff', 'Cliff, Baxter'] },    
{ name: 'Beatty, George', aliases: [] },
{ name: 'Bhatnagar, Sanjay', aliases: [] },
{ name: 'Bibi, Philippe A', aliases: [] },
{ name: 'Blachman, Jeremy', aliases: [] },
{ name: 'Bradley, Rob', aliases: [] },
{ name: 'Brown, Katherine', aliases: [] },
{ name: 'Buy, Rick', aliases: [] },        
{ name: 'Causey, Richard', aliases: ['Causey@enron, Richard', 'Richard, Causey',] },  
{ name: 'Chase, Anthony R', aliases: [] },
{ name: 'Cindy, Olson', aliases: [] },
{ name: 'Cliff, Baxter', aliases: [] },
{ name: 'Committee, Executive', aliases: ['Committee, Enron Executive', ] },
{ name: 'Craven, Judy', aliases: [] },
{ name: 'Culver, Anne', aliases: [] },
{ name: 'Delainey, David W', aliases: [] },
{ name: 'Derrick, James', aliases: [] },
{ name: 'Dussler, Bob', aliases: [] },
{ name: 'Everett, C Richard', aliases: [] },
{ name: 'Fastow, Andrew S', aliases: ['Fastow, Andy','Andrew, Fastow',] },
{ name: 'Fitch, Gary', aliases: [] },
{ name: 'Fitzgerald, Jay', aliases: [] },
{ name: 'Fleming, Rosalee', aliases: ['Rosalee, Fleming', ] },
{ name: 'Frevert, Mark', aliases: ['Mark, Frevert',] },
{ name: 'Garten, Jeffrey', aliases: ['Jeffrey, Garten',] },
{ name: 'Groscrand, Vanessa', aliases: [] },
{ name: 'Heilmeier, George', aliases: ['Heilmeier, Dr George',] },
{ name: 'Herrold, Beau', aliases: [] },
{ name: 'Hillings, Joe', aliases: [] },
{ name: 'Hughes, James', aliases: ['A, Hughes James'] },
{ name: 'Jr, Bowen', aliases: [] },
{ name: 'Kean, Steven J', aliases: [] },
{ name: 'Keepers, Sally', aliases: [] },
{ name: 'Koenig, Mark', aliases: [] },     
{ name: 'Lauderback, Bill', aliases: [] },
{ name: 'Lay, Elizabeth', aliases: [] },
{ name: 'Lay, Kenneth', aliases: ['lay@enroncom, Ken', 'klay@enron.com.','klay@enron','ken', 'Lay/enron, Kenneth L', 'Lay@enron, Ken', 'lay', 'kennethlay@enron.com', 'kenneth_lay@enron.net','kenneth.l.lay@enron.com', 'kenneth', 'ken_lay@enron.net', 'ken.lay@enron.com', 'Ken, Lay','ken_lay@enron.com', 'Lay@enron, Kenneth','Lay, Kenneth L','Chairman, Ken Lay - Office Of The','kenneth.lay@enron.com', 'kenneth_lay@enron.com', 'layk@enron.com', 'klay@enron.com', 'Lay, Ken', 'Kenneth, Lay'], },
{ name: 'Lay, Linda', aliases: ['Linda, Lay', 'Lay, Linda P', 'mrslinda@lplpi.com',] },
{ name: 'Lay, Mark', aliases: [ 'mark.lay@enron.com', 'mark','Lay, Mark K',] },
{ name: 'Lay, Sharon', aliases: [] },
{ name: 'Love, Ben F', aliases: [] },
{ name: 'Mark, Koenig', aliases: [] },
{ name: 'Mccarty, Arlene', aliases: [] },
{ name: 'Mcconnell, Mike', aliases: [] },
{ name: 'Mcdonald, Rebecca', aliases: [] },
{ name: 'Mcmahon, Jeffrey', aliases: ['Jeffrey, Mcmahon'] },
{ name: 'Milken, Michael', aliases: [] },
{ name: 'Moore, Charles', aliases: [] },
{ name: 'Moore, Preston', aliases: [] },
{ name: 'Piernot, William W', aliases: [] },
{ name: 'Rieker, Paula', aliases: [] },    
{ name: 'Sandherr, Cynthia', aliases: [] },
{ name: 'Skilling, Jeff', aliases: ['Skilling@enron, Jeff','Jeff, Skilling', 'Skilling, Jeffrey'] },
{ name: 'Smith, Glenn', aliases: [] },
{ name: 'Smith, Linda', aliases: [] },
{ name: 'Sunil, Abraham', aliases: [] },
{ name: 'Sutton, Joseph W', aliases: [] },
{ name: 'Treas, Hou Ir', aliases: [] },
{ name: 'Trulove, William G', aliases: [] },
{ name: 'Vermeil, Christophe', aliases: [] },
{ name: 'Wells, Tori L', aliases: [] },
{ name: 'Whalley, Greg', aliases: ['gwhalle@enron.com','gwhalley@enron.com','Greg, Whalley'] },
{ name: 'Willerson, James', aliases: ['James, Willerson'] },
{ name: 'alfred.gilman@email.swmed.edu', aliases: ['alfred.gilman@utsouthwestern.edu',] },
{ name: 'allstudents@howard.edu', aliases: ['allemployees@howard.edu','allstudents',] },
{ name: 'babbio@verizon.com', aliases: ['babbio@bellatlantic.com',] },
{ name: 'george.fisher@kodak.com', aliases: [] },
{ name: 'jterzuoli@ibjwhitehall.com', aliases: [] },

]

export const aliasMap = new Map()
contacts.map((contact) => {
  contact.aliases.map((alias) => {
    aliasMap.set(alias, contact.name)
  })
  aliasMap.set(contact.name, contact.name)
})
