import { PSTMessage } from 'pst-extractor'

// https://books.google.com/books?id=CeapJz_amLUC&pg=SL1-PA25&lpg=SL1-PA25&dq=enron+glossary&source=bl&ots=ZIvVX780A0&sig=ACfU3U1As4CgzXi4THiPraSuiTeh_vVpjg&hl=en&sa=X&ved=2ahUKEwiVypmsga_pAhWHsJ4KHXCbDfcQ6AEwCHoECAoQAQ#v=onepage&q=enron%20glossary&f=false

export const keyTerms = [
  'Avici',
  'Azurix',
  'Backbone',
  'Blue Dog',
  'Braveheart',
  'Catalytica',
  'Cortez',
  'Cuiaba',
  'ENA CLO',
  'Fishtail',
  'Margaux1',
  'Merlin',
  'Merlin',
  'Nowa Sarzyna',
  'Osprey',
  'Rawhide',
  'Rythms',
  'Southampton',
  'TNPC',
  'TNPC1',
  'Yosemite',
  'apache',
  'bammel',
  'bankrupt',
  'bankruptcy',
  'bobcat',
  'california',
  'campsie',
  'cayman',
  'chewco',
  'condor',
  'criminal',
  'death',
  'deathstar',
  'ebs',
  'electricity',
  'fraud',
  'granite',
  'grizzly',
  'harrier',
  'herron',
  'jedi',
  'litigation',
  'ljm',
  'ljm1',
  'ljm2',
  'mahonia',
  'maliseet',
  'mangas',
  'monopoly',
  'new power',
  'ojibway',
  'oregon',
  'porcupine',
  'preservation',
  'pronghorn',
  'raptor',
  'raptors',
  'renegade',
  'retirement',
  'ricochet',
  'roadrunner',
  'shorty',
  'shutdown',
  'sidewinder',
  'snohomish',
  'stanley',
  'star',
  'steele',
  'swap',
  'talon',
  'tammy',
  'teresa',
  'timberwolf',
  'tonya',
  'trutta',
  'tularosa',
  'valhalla',
  'valkyrie',
  'valor',
  'velocity',
  'whitewing',
]

export function hasKeyTerms(email: PSTMessage): boolean {
  for (const term of keyTerms) {
    if (email.body.indexOf(term) >= 0 || email.subject.indexOf(term) >= 0)
      return true
  }
  return false
}
